project_name: bf

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod download

build:
  env:
    - CGO_ENABLED=0
  ldflags:
    - -s -w -X github.com/browsefile/backend/v0.1.0/version.Version={{ .Version }} -X github.com/browsefile/backend/v0.1.0/version.CommitSHA={{ .ShortCommit }}
  main: src/main.go
  binary: bf
  goos:
    - darwin
    - linux
    - windows
    - freebsd
    - netbsd
    - openbsd
    - dragonfly
    - solaris
  goarch:
    - amd64
    - 386
    - arm
    - arm64
    - mips
    - mipsle
  goarm:
    - 5
    - 6
    - 7
  ignore:
    - goos: darwin
      goarch: 386
    - goos: openbsd
      goarch: arm
    - goos: freebsd
      goarch: arm
    - goos: netbsd
      goarch: arm
    - goos: solaris
      goarch: arm

archives:
  -
    name_template: "{{.Os}}-{{.Arch}}{{if .Arm}}v{{.Arm}}{{end}}-{{ .ProjectName }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

dockers:
  -
    goos: linux
    goarch: amd64
    goarm: ''
    image_templates:
      - "filebrowser/filebrowser:latest"
      - "filebrowser/filebrowser:{{ .Tag }}"
      - "filebrowser/filebrowser:v{{ .Major }}"
    extra_files:
      - .docker.json