project_name: bf

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod download

build:
  env:
    - CGO_ENABLED=0
  ldflags:
    - -s -w -X github.com/browsefile/backend/src/cnst.Version={{ .Version }}
  main: src/main.go
  binary: bf
  goos:
    - linux
    - freebsd
    - netbsd
    - openbsd
  goarch:
    - amd64
    - 386
    - arm
    - arm64
    - mips
    - mipsle
    - mips64
    - mips64le
  goarm:
    - 5
    - 6
    - 7
  ignore:
    - goos: openbsd
      goarch: arm
    - goos: freebsd
      goarch: arm
    - goos: netbsd
      goarch: arm
    - goos: openbsd
      goarch: arm64
    - goos: freebsd
      goarch: arm64
    - goos: netbsd
      goarch: arm64
    - goos: openbsd
      goarch: mips
    - goos: freebsd
      goarch: mips
    - goos: netbsd
      goarch: mips
    - goos: openbsd
      goarch: mipsle
    - goos: freebsd
      goarch: mipsle
    - goos: netbsd
      goarch: mipsle
    - goos: openbsd
      goarch: mips64
    - goos: freebsd
      goarch: mips64
    - goos: netbsd
      goarch: mips64
    - goos: openbsd
      goarch: mips64le
    - goos: freebsd
      goarch: mips64le
    - goos: netbsd
      goarch: mips64le

archives:
  - name_template: "{{.Os}}-{{.Arch}}{{if .Arm}}v{{.Arm}}{{end}}-{{ .ProjectName }}"

    files:
      - browsefile.json
      - bfconvert.sh
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
